apiVersion: v1
kind: Secret
metadata: 
  name: aviate-secrets
type: Opaque
stringData: 
  JWT_SECRET: your-super-secret_jwt-key
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: securepassword
  POSTGRES_DB: aviate-db
  REDIS_PASSWORD: ""